name: Terraform EKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Dev

    steps:

      - name: Checkout
        uses: actions/checkout@v4

  
        
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
         role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
         aws-region: us-west-2

     

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=eks.tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve eks.tfplan
